version: '3.4'

services:
  o10.nomy:
    image: muaddibco/o10nomy:latest
    ports:
    - 5004:80
    environment:
      - DBSERVER=db
      - O10PORTALSERVICENAME=o10.portal.webapp
      
  o10.portal.webapp:
    image: muaddibco/o10portal:latest
    environment:
      - ASPNETCORE_URLS=http://+:80
      - GWSERVICENAME=o10.gateway.webapp
      - DBSERVER=db
    ports:
    - 5003:80

  o10.gateway.webapp:
    image: muaddibco/o10gateway:latest
    environment:
      - ASPNETCORE_URLS=http://+:80
      - GWSERVICENAME=o10.gateway.webapp
      - NODESERVICENAME=o10.node.webapp
      - GATEWAYKEY=7109020FC572C7D84DB0BFE41595454EA2B8BEA65A8EAE398F0833D54DA1EA0B
      - DBSERVER=db
    ports:
    - 5002:80

  o10.node.webapp:
    image: muaddibco/o10node:latest
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DBSERVER=db
    ports:
    - 5001:80


  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "p@ssword1"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433